### ISSUE TITLE
Session::nextEvent interprets timeouts under 1us as infinite

### ISSUE THREAD

**Issue by rt12** [bloomberg/blazingmq#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Timeout under 1us (for example, 100ns) is interpreted as infinite timeout

### Expected Behavior

Only zero timeout should be interpreted as "infinite"

### Steps To Reproduce

Create a sync session
Pass 1ns as the timeout to Session::nextEvent
The call will block instead of returning immediately

### BlazingMQ Version

1.13.3

**Comment by 678098** [comment]
Thank you @rt12, we will address

@syuzvinsky could you fix this?

The problem is here:
https://github.com/bloomberg/blazingmq/blob/de10ba9d4993208bd9140337bbd432a45c4f27b7/src/groups/bmq/bmqa/bmqa_session.cpp#L1483-L1488

Possible to use `totalNanoseconds` for smallest time granularity
https://bloomberg.github.io/bde-resources/doxygen/bde_api_prod/classbsls_1_1TimeInterval.html#a23405ad7b0178131af8cdc2c2d7015ab
