### ISSUE TITLE
Documentation is inconsistent on compression of message properties

### ISSUE THREAD

**Issue by Cartroo** [bloomberg/blazingmq#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the *Compression* section of the documentation, the *Summary* section states:

> Producer applications can indicate to the BlazingMQ SDK to compress a message. BlazingMQ SDK will compress the message (both payload and properties) before sending it to the BlazingMQ back-end.

Later on the same page in the *Important Notes* section, there is an apparent contradiction:

> Only the message payload is compressed. Message properties are not compressed in order to ensure that the BlazingMQ message broker can read the properties efficiently if needed (for example, properties are read by the broker for evaluating subscriptions).

I'm assuming both of these can't be correct — properties cannot be both compressed and not compressed. (I mean they could be, but it would seem surprising)

### Expected Behavior

The documentation is self-consistent.

### Steps To Reproduce

1. Read [the compression documentation](https://bloomberg.github.io/blazingmq/docs/features/compression/).

### BlazingMQ Version

1.0.0

**Comment by 678098** [comment]
Hi @Cartroo thank you for the report, it's inconsistency indeed. We'll update docs to make it more clear.

And just some info about compression. Actually, we have both modes:
- Payload + message properties - it's Version1.
- Only payload - it's Version2, known as `MESSAGE_PROPERTIES_EX`: https://github.com/bloomberg/blazingmq/blob/ca6491f69eea8d91733fa36ef3e82c4facc734fc/src/groups/bmq/bmqp/bmqp_protocol.cpp#L274

Version V1 is the first version, but it was not well suited to use with subscriptions feature. When message properties area is compressed, we need to spend processing time on the primary node to decompress it for each message to evaluate expressions. It's a performance critical path, so we have to do some optimizations.

That's why version V2 appeared. We don't spend time on decompressing, because message properties area is not compressed. Also there is a change in protocol in V2, we don't encode length of each property, instead we encode offsets from the properties area start. It allows to jump to each property value in a blob with O(1) complexity, which is useful when evaluating expressions.
